# Generated by Django 5.0.7 on 2024-08-17 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_education'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='userprofile',
            new_name='user',
        ),
    ]
